[project]
name = "dunning-kruger"
version = "0.0.1"
description = "Monte Carlo simulation of the Dunning and Kruger experiment."
authors = [
    {name = "Evgeny Ivanov", email = "ivanov.evgeny.n@gmail.com"},
]
dependencies = ["numpy"]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
[tool.pdm.dev-dependencies]
lint = ["ruff", "pyright"]
